# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fraud.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fraud.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66raud.proto\x12\x05\x66raud\"\xc3\x01\n\x0fTransactionInfo\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\t\x12\x13\n\x0bmerchant_id\x18\x06 \x01(\t\x12\x16\n\x0epayment_method\x18\x07 \x01(\t\x12%\n\x08location\x18\x08 \x01(\x0b\x32\x13.fraud.LocationInfo\"3\n\x0cLocationInfo\x12\x12\n\nip_address\x18\x01 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x02 \x01(\t\"F\n\x0eRiskAssessment\x12\x10\n\x08is_fraud\x18\x01 \x01(\x08\x12\x12\n\nrisk_score\x18\x02 \x01(\x02\x12\x0e\n\x06reason\x18\x03 \x01(\t2\\\n\x15\x46raudDetectionService\x12\x43\n\x10\x43heckTransaction\x12\x16.fraud.TransactionInfo\x1a\x15.fraud.RiskAssessment\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTIONINFO']._serialized_start=23
  _globals['_TRANSACTIONINFO']._serialized_end=218
  _globals['_LOCATIONINFO']._serialized_start=220
  _globals['_LOCATIONINFO']._serialized_end=271
  _globals['_RISKASSESSMENT']._serialized_start=273
  _globals['_RISKASSESSMENT']._serialized_end=343
  _globals['_FRAUDDETECTIONSERVICE']._serialized_start=345
  _globals['_FRAUDDETECTIONSERVICE']._serialized_end=437
# @@protoc_insertion_point(module_scope)
