# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fraud_pb2 as fraud__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fraud_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FraudDetectionServiceStub(object):
    """The Service Definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckTransaction = channel.unary_unary(
                '/fraud.FraudDetectionService/CheckTransaction',
                request_serializer=fraud__pb2.TransactionInfo.SerializeToString,
                response_deserializer=fraud__pb2.RiskAssessment.FromString,
                _registered_method=True)


class FraudDetectionServiceServicer(object):
    """The Service Definition
    """

    def CheckTransaction(self, request, context):
        """A synchronous RPC call: The Gateway sends a Transaction, gets a Risk Assessment
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FraudDetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckTransaction,
                    request_deserializer=fraud__pb2.TransactionInfo.FromString,
                    response_serializer=fraud__pb2.RiskAssessment.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fraud.FraudDetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fraud.FraudDetectionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FraudDetectionService(object):
    """The Service Definition
    """

    @staticmethod
    def CheckTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fraud.FraudDetectionService/CheckTransaction',
            fraud__pb2.TransactionInfo.SerializeToString,
            fraud__pb2.RiskAssessment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
